### ISSUE TITLE
Change date formatting routine to use formatDateString

### ISSUE THREAD

**Issue by dullroar** [dullroar/TW5-atomfeed#5]
Change date formatter to use TW's *formatDateString*, since the internal representation of a TW date may change.

>see:  core/modules/utlis/utils.js

>exports.formatDateString = function(date,template)

>`$tw.utils.formatDateString(new Date, "YYYY-MMM")`
>will give you "2015-January"

**Comment by sukima** [comment]
I think this is fixed by #7
