### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by sukima** [dullroar/TW5-atomfeed#9]
With #7 and #8 the readme needs to be updated.

**Comment by gesundelehre** [comment]
Is this part in the readme still up to date?

> Change the URL in dullroar/atomfeed/atomserver.tid from http://dullroar.com/ to your own site's URL. Note that the ending / is required.

Because i cannot find the file called "atomserver.tid"
Am I missing something?

Thanks

**Comment by dullroar** [comment]
You are not missing anything. This code got a major refactor by @sukima last year. Looking at it (I no longer use TW, so I have basically given commit control over to @sukima), I believe now you do the configuration for the feed in the `config.tid`.

**Comment by sukima** [comment]
Started a branch. Will work on fleshing out the details soon.

https://github.com/dullroar/TW5-atomfeed/tree/docs/readme

**Comment by gesundelehre** [comment]
Thanks very much!
Looking forward to hear more about the progress of it

Greetings

**Comment by sukima** [comment]
@gesundelehre I have a Pull Request with an updated readme at #12

**Comment by openmedi** [comment]
So… is the readme updated now? Should this be closed? (If it is updated and stays open, it's kinda confusing for us newcomers…)

**Comment by sukima** [comment]
I thought this *did* get closed. `#GitHubUserFail`
